# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sentiment.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sentiment.proto',
  package='sentiment',
  syntax='proto3',
  serialized_pb=_b('\n\x0fsentiment.proto\x12\tsentiment\" \n\x10SentimentRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"4\n\x0eSentimentReply\x12\x10\n\x08positive\x18\x01 \x01(\x02\x12\x10\n\x08negative\x18\x02 \x01(\x02\x32\x9f\x01\n\tSentiment\x12\x43\n\x07\x41nalyze\x12\x1b.sentiment.SentimentRequest\x1a\x19.sentiment.SentimentReply\"\x00\x12M\n\rAnalyzeStream\x12\x1b.sentiment.SentimentRequest\x1a\x19.sentiment.SentimentReply\"\x00(\x01\x30\x01\x62\x06proto3')
)




_SENTIMENTREQUEST = _descriptor.Descriptor(
  name='SentimentRequest',
  full_name='sentiment.SentimentRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='sentiment.SentimentRequest.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=62,
)


_SENTIMENTREPLY = _descriptor.Descriptor(
  name='SentimentReply',
  full_name='sentiment.SentimentReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='positive', full_name='sentiment.SentimentReply.positive', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='negative', full_name='sentiment.SentimentReply.negative', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=116,
)

DESCRIPTOR.message_types_by_name['SentimentRequest'] = _SENTIMENTREQUEST
DESCRIPTOR.message_types_by_name['SentimentReply'] = _SENTIMENTREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SentimentRequest = _reflection.GeneratedProtocolMessageType('SentimentRequest', (_message.Message,), dict(
  DESCRIPTOR = _SENTIMENTREQUEST,
  __module__ = 'sentiment_pb2'
  # @@protoc_insertion_point(class_scope:sentiment.SentimentRequest)
  ))
_sym_db.RegisterMessage(SentimentRequest)

SentimentReply = _reflection.GeneratedProtocolMessageType('SentimentReply', (_message.Message,), dict(
  DESCRIPTOR = _SENTIMENTREPLY,
  __module__ = 'sentiment_pb2'
  # @@protoc_insertion_point(class_scope:sentiment.SentimentReply)
  ))
_sym_db.RegisterMessage(SentimentReply)



_SENTIMENT = _descriptor.ServiceDescriptor(
  name='Sentiment',
  full_name='sentiment.Sentiment',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=119,
  serialized_end=278,
  methods=[
  _descriptor.MethodDescriptor(
    name='Analyze',
    full_name='sentiment.Sentiment.Analyze',
    index=0,
    containing_service=None,
    input_type=_SENTIMENTREQUEST,
    output_type=_SENTIMENTREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='AnalyzeStream',
    full_name='sentiment.Sentiment.AnalyzeStream',
    index=1,
    containing_service=None,
    input_type=_SENTIMENTREQUEST,
    output_type=_SENTIMENTREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SENTIMENT)

DESCRIPTOR.services_by_name['Sentiment'] = _SENTIMENT

# @@protoc_insertion_point(module_scope)
